# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMapAPIPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  
  # Pods for GoogleMapAPIPractice

  target 'GoogleMapAPIPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoogleMapAPIPracticeUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
